### ISSUE TITLE
Add "optimize images" task

### ISSUE THREAD

**Issue by jbmoelker** [voorhoede/front-end-guide#10]
* minify bitmap images
* minify vector images (svg)
* create sprites? (Iconirzr?)

**Comment by phortuin** [comment]
possibly use tinypng API? https://tinypng.com/developers

**Comment by jpcarmona** [comment]
@phortuin I think 500 requests per month its too little. Even the 3,500 per 15e would not be enough, if we are using the front-end-guide regularly.

Why just not use some plugin for image optimization for example [gulp-image](https://www.npmjs.com/package/gulp-image)? What's the benefit of using the tinypng API?

**Comment by phortuin** [comment]
tinypng is just very good at PNG optimization. it is based on pngquant (http://pngquant.org/). if the file size & quality of gulp-image is similar it's easier to just implement that, otherwise it might be worth it to consider tinypng. they only charge if the image size can be reduced (which should only be the case the first time a build is made of non-optimized images), but we'd have to test in different scenarios. maybe it's worth the time to do a little proof of concept?

**Comment by phortuin** [comment]
for a PoC we could use this: https://www.npmjs.com/package/imagemin-pngquant

**Comment by jpcarmona** [comment]
Well if they only charge if the image can be reduced that a different mindset. But I would of course prefer not to be dependent on an external service, if we can. I think that's the main reason to not go to tinypng.

**Comment by decrek** [comment]
I think we should use `gulp-imagemin`. It is based on the same tools as tinypng, doesn't need api keys, or internet connection. It is used for PNG, JPEG, GIF and SVG optimisation. In fact I will implement this today.
